# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ee4fa86ea2dfdcbf508f2fc19b6230a5b0f170512f81c28cfe6f2314046d4430477dc0801419457d4569e7b0d33c01c2d5d428d47369198c059d19d63b2f9ef

test:
  secret_key_base: f7e5033dcc79eba1cedb6c09cab22d95224f2d84de5ec73a90e0c26ae7bb2d9ddcc9cd97b881c0371c3e6f150f579be61d1482c226ad1cb5d09161816b930a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
